name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SELENIUM_REMOTE_URL: http://your-selenium-hub:4444/wd/hub
      APP_URL: "http://localhost:5000"
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit & integration tests
        run: pytest tests/unit tests/integration -q

  e2e:
    runs-on: ubuntu-latest
    needs: tests
    services:
      selenium:
        image: selenium/standalone-chrome:115.0
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app in background
        env:
          FLASK_APP: app.app:create_app
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &

      - name: Run E2E tests
        env:
          SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
          APP_URL: http://localhost:5000
        run: |
          sleep 5
          pytest tests/e2e/test_homepage.py -q
